apiVersion: apps/v1
kind: Deployment
metadata:
        name: flasktest

spec:
        replicas: 3
        selector:
                matchLabels:
                        app: flasktest
        template:
                metadata:
                        labels:
                                app: flasktest
                                env: stage
                spec:
                        containers:
                        - name: flasktest
                          image: gcr.io/i-argon-287805/flasktest
                          resources:
                                  requests:
                                          memory: "64Mi"
                                          cpu: "250m"
                                  limits:
                                          memory: "128Mi"
                                          cpu: "500m"

                          ports:
                                   - containerPort: 5000



