apiVersion: v1
kind: Service
metadata:
        name: webserver
spec:
        type: LoadBalancer
        selector:
                app: flasktest
        ports:
                - port: 5000
                  targetPort: 5000
                  protocol: TCP
